# Generated by Django 5.1.1 on 2024-09-26 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_time']},
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 4, 25, 1, 128859, tzinfo=datetime.timezone.utc)),
        ),
    ]
